name: mazaq windows

on:
  push:
    branches: [ main ]

jobs:
  build_windows:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: استنساخ المستودع
        uses: actions/checkout@v4

      - name: إعداد Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.9'
          
      - name: download packages 
        run: flutter clean
        
      - name: upgrade flutter
        run: flutter upgrade

      - name: download packages 
        run: flutter pub get

      - name: Windows Release
        run: flutter build windows --release 

      - name: Copy APK to artifacts folder
        run: |
          cp sqlite3.dll build/windows/x64/runner/Release/

      - name: upload Windows  (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/x64/runner/Release/